repos:
    # Validación de paquetes de terceros para el isort
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
        # Declaramos donde se encuentra el código
        args: [--application-directorie=crawler]
    # validación de paquetes tengab el siguiente orden
    # FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
    # https://www.python.org/dev/peps/pep-0008/#imports
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
    -   id: isort
        additional_dependencies: ['toml']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
        # Validar que al final de un documento exista un salto de linea
    -   id: end-of-file-fixer
        # Validar que al final una linea no exista un espacio
    -   id: trailing-whitespace
        # Validamos los requirements
    -   id: requirements-txt-fixer
        # Simply check whether files parse as valid python.
    -   id: check-ast
    # Validar el Flake 8 de archivos que se cambiaron
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
